config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'thanks#index'
  resources :thanks, only: [:index, :new, :create]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/thank.rb
class Thank < ActiveRecord::Base

  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  validates :sender_id, :presence => true
  validates :recipient_id, :presence => true
  validates :message, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :sent_thanks, :class_name => 'Thank', :foreign_key => 'sender_id'
  has_many :received_thanks, :class_name => 'Thank', :foreign_key => 'recipient_id'


  def all_thanks
    sent_thanks + received_thanks
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController

  before_action :authenticate_user!

  def index
    if params["filter"] = "me"
      @thanks = current_user.all_thanks
    elsif params["filter"] == "friends"
      #THIS SHOULD ONLY DO FRIENDS WHEN FRIENDS ARE A THING
      @thanks = current_user.all_thanks
    else
      @thanks = Thanks.all
    end
  end

  def new
    @thank = Thank.new
  end

  def create
    @thank = Thank.create(thank_params)
    if @thank.save
      redirect_to thanks_path
    else
      render action: 'new', alert: "couldnt give your thanks"
    end
  end
private

  def thank_params
    params.require(:thank).permit(:recipient_id, :sender_id, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thx</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/thanks/_thank.html.erb
<h2><%= thank.inspect %></h2>

app/views/thanks/index.html.erb
<h1>home</h1>

<%= current_user.inspect %>

<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>

<%= link_to("give thanks", new_thank_path) %>
<hr>
<%  @thanks.each do |thank| %>
  <%= render partial: "thank", locals: {thank: thank} %>
  <hr>
<% end %>

app/views/thanks/new.html.erb
<%= form_for @thank do |f| %>
    recipient_id : <%= f.number_field :recipient_id %>
    message : <%= f.text_field :message %>
    <%= f.hidden_field :sender_id, value: current_user.id %>

    <%= f.submit %>
<% end %>